/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPharmacyRouteImport } from './routes/_authenticated/pharmacy'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedDoctorsRouteImport } from './routes/_authenticated/doctors'
import { Route as AuthenticatedDigitalTwinRouteImport } from './routes/_authenticated/digital-twin'
import { Route as AuthenticatedCareRouteImport } from './routes/_authenticated/care'
import { Route as AuthenticatedAskOmniRouteImport } from './routes/_authenticated/ask-omni'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPharmacyRoute = AuthenticatedPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorsRoute = AuthenticatedDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDigitalTwinRoute =
  AuthenticatedDigitalTwinRouteImport.update({
    id: '/digital-twin',
    path: '/digital-twin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCareRoute = AuthenticatedCareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAskOmniRoute = AuthenticatedAskOmniRouteImport.update({
  id: '/ask-omni',
  path: '/ask-omni',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/ask-omni': typeof AuthenticatedAskOmniRoute
  '/care': typeof AuthenticatedCareRoute
  '/digital-twin': typeof AuthenticatedDigitalTwinRoute
  '/doctors': typeof AuthenticatedDoctorsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/reports': typeof AuthenticatedReportsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/ask-omni': typeof AuthenticatedAskOmniRoute
  '/care': typeof AuthenticatedCareRoute
  '/digital-twin': typeof AuthenticatedDigitalTwinRoute
  '/doctors': typeof AuthenticatedDoctorsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/ask-omni': typeof AuthenticatedAskOmniRoute
  '/_authenticated/care': typeof AuthenticatedCareRoute
  '/_authenticated/digital-twin': typeof AuthenticatedDigitalTwinRoute
  '/_authenticated/doctors': typeof AuthenticatedDoctorsRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/pharmacy': typeof AuthenticatedPharmacyRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/appointments'
    | '/ask-omni'
    | '/care'
    | '/digital-twin'
    | '/doctors'
    | '/insights'
    | '/pharmacy'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/appointments'
    | '/ask-omni'
    | '/care'
    | '/digital-twin'
    | '/doctors'
    | '/insights'
    | '/pharmacy'
    | '/reports'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/appointments'
    | '/_authenticated/ask-omni'
    | '/_authenticated/care'
    | '/_authenticated/digital-twin'
    | '/_authenticated/doctors'
    | '/_authenticated/insights'
    | '/_authenticated/pharmacy'
    | '/_authenticated/reports'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pharmacy': {
      id: '/_authenticated/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AuthenticatedPharmacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctors': {
      id: '/_authenticated/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AuthenticatedDoctorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/digital-twin': {
      id: '/_authenticated/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof AuthenticatedDigitalTwinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/care': {
      id: '/_authenticated/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof AuthenticatedCareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ask-omni': {
      id: '/_authenticated/ask-omni'
      path: '/ask-omni'
      fullPath: '/ask-omni'
      preLoaderRoute: typeof AuthenticatedAskOmniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedAskOmniRoute: typeof AuthenticatedAskOmniRoute
  AuthenticatedCareRoute: typeof AuthenticatedCareRoute
  AuthenticatedDigitalTwinRoute: typeof AuthenticatedDigitalTwinRoute
  AuthenticatedDoctorsRoute: typeof AuthenticatedDoctorsRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedPharmacyRoute: typeof AuthenticatedPharmacyRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedAskOmniRoute: AuthenticatedAskOmniRoute,
  AuthenticatedCareRoute: AuthenticatedCareRoute,
  AuthenticatedDigitalTwinRoute: AuthenticatedDigitalTwinRoute,
  AuthenticatedDoctorsRoute: AuthenticatedDoctorsRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedPharmacyRoute: AuthenticatedPharmacyRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
